name: Setup wrk
description: Setup wrk in local workspace

runs:
  using: composite

  steps:
    - name: Install APT dependencies
      shell: bash
      run: |
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          git

    - name: Checkout wrk
      shell: bash
      run: |
        rm -rf ./wrk
        ls -la
        pwd
        git clone https://github.com/wg/wrk.git ./wrk

    - name: Build wrk
      shell: bash
      working-directory: wrk
      run: |
        make
        sudo cp wrk /usr/local/bin
