name: HTTP benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        framework:
        - babashka
        - expressjs
        - giraffe
        - golang

    steps:
    - uses: actions/checkout@v4

    - name: Setup Babashka
      if: matrix.framework == 'babashka'
      run: |
        bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

    - name: Setup Go
      uses: actions/setup-go@v2
      if: matrix.framework == 'golang'
      with:
        go-version: 1.22.x

    - name: Setup .NET
      if: matrix.framework == 'giraffe'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      if: matrix.framework == 'expressjs'
      with:
        node-version: 18.x

    - name: Benchmark ${{ matrix.framework }}
      working-directory: http
      run: |
        ./benchmark.bash ${{ matrix.framework }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.framework }}-report
        path: ./http/${{ matrix.framework }}.report
