name: HTTP benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        framework:
        - babashka-httpkit
        - cl-ningle
        - csharp-minimal
        - csharp-mvc
        - guile-2
        - guile-3
        - javascript-expressjs
        - fsharp-giraffe
        - golang-http
        - racket-servlet
        - rust-rocket
        
    steps:
    - uses: actions/checkout@v4

    - name: Setup Babashka
      if: startsWith(matrix.framework, 'babashka-')
      run: |
        bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

    - name: Setup CL
      if: startsWith(matrix.framework, 'cl-')
      run: |
        sudo apt-get install -y sbcl
        sbcl --version

    - name: Setup Go
      uses: actions/setup-go@v5
      if: startsWith(matrix.framework, 'golang-')
      with:
        cache-dependency-path: http/${{ matrix.framework }}/go.sum
        go-version-file: http/${{ matrix.framework }}/go.mod
    
    - name: Setup Guile 2
      if: startsWith(matrix.framework, 'guile-2')
      run: |
        sudo apt-get install -y guile-2.2
        guile --version
    
    - name: Setup Guile 3
      if: startsWith(matrix.framework, 'guile-3')
      run: |
        sudo apt-get install -y guile-3.0
        guile --version

    - name: Setup .NET
      if: startsWith(matrix.framework, 'csharp-') || startsWith(matrix.framework, 'fsharp-')
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Setup Node.js
      if: startsWith(matrix.framework, 'javascript-')
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Setup Racket
      if: startsWith(matrix.framework, 'racket-')
      run: |
        sudo apt-get install -y racket

    - name: Setup Rust
      if: startsWith(matrix.framework, 'rust-')
      run: |
        rustup toolchain install nightly
        rustup default nightly
        cargo version

    - name: Benchmark ${{ matrix.framework }}
      working-directory: http
      run: |
        ./benchmark.bash ${{ matrix.framework }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.framework }}-report
        path: ./http/${{ matrix.framework }}.report
